import { Inter } from "next/font/google";
import "./globals.css";
import SidebarNav from "./components/SidebarNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Propensity",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en' className='h-full'>
			<body className={inter.className}>
				<SidebarNav />
				<main className='py-10 lg:pl-72'>
					<div className='px-4 sm:px-6 lg:px-8'>{children}</div>
				</main>
			</body>
		</html>
	);
}
